"""Protein-pair cases. A case is a YAML file naming the two UniProt accessions and,
optionally, an MD score file. `cases/fat10_mad2.yaml` is the v1 case study;
`benchmark/*.yaml` are the benchmark pairs (generated by scripts/make_benchmark_cases.py).

`ground_truth` is read only by the scorer and by agent/leakage.py (to know what to
hide); no tool ever returns it to the agent.
"""
from __future__ import annotations
from contextvars import ContextVar
import re
from dataclasses import dataclass
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CASE_PATH = ROOT / "cases" / "fat10_mad2.yaml"


@dataclass(frozen=True)
class Case:
    id: str
    name_a: str
    uniprot_a: str
    name_b: str
    uniprot_b: str
    goal: str
    literature_query: str
    benchmark: bool = False
    md_scores: str | None = None            # None -> the MD tool reports `pending`
    ground_truth: dict | None = None        # scorer / leak filter only
    custom: bool = False                    # a pair typed in by a user: generic tools, no held-out complex

    @property
    def generic(self) -> bool:
        """Pair mode: pending MD/debate, UniProt feature table, no FAT10-specific claims."""
        return self.benchmark or self.custom


def load_case(path) -> Case:
    d = yaml.safe_load(Path(path).read_text(encoding="utf-8"))
    return Case(id=d["id"], name_a=d["name_a"], uniprot_a=d["uniprot_a"],
                name_b=d["name_b"], uniprot_b=d["uniprot_b"],
                goal=" ".join(str(d["goal"]).split()),
                literature_query=d["literature_query"],
                benchmark=bool(d.get("benchmark", False)),
                md_scores=d.get("md_scores"),
                ground_truth=d.get("ground_truth"))


def default_case() -> Case:
    return load_case(DEFAULT_CASE_PATH)


def find_case(case_id: str) -> Case:
    for folder in ("cases", "benchmark"):
        p = ROOT / folder / f"{case_id}.yaml"
        if p.exists():
            return load_case(p)
    raise KeyError(f"no case {case_id!r} in cases/ or benchmark/")


def load_benchmark() -> list[Case]:
    return [load_case(p) for p in sorted((ROOT / "benchmark").glob("*.yaml"))]


_ACTIVE: ContextVar[Case | None] = ContextVar("active_case", default=None)


def set_active_case(case: Case | None):
    """Returns a token for reset_active_case()."""
    return _ACTIVE.set(case)


def reset_active_case(token) -> None:
    _ACTIVE.reset(token)


def active_case() -> Case:
    """The case the tools act on; FAT10-MAD2 (v1 behaviour) when none is set."""
    return _ACTIVE.get() or default_case()


# official UniProt accession pattern (https://www.uniprot.org/help/accession_numbers)
_ACC = re.compile(r"^([OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z][0-9]([A-Z][A-Z0-9]{2}[0-9]){1,2})$")


def custom_case(uniprot_a: str, uniprot_b: str, name_a: str | None = None,
                name_b: str | None = None) -> Case:
    """A protein pair typed in by a user. Raises ValueError on a malformed accession."""
    a, b = uniprot_a.strip().upper(), uniprot_b.strip().upper()
    for acc in (a, b):
        if not _ACC.match(acc):
            raise ValueError(f"{acc!r} is not a valid UniProt accession")
    na, nb = (name_a or a).strip(), (name_b or b).strip()
    goal = (f"Investigate where {na} (UniProt {a}) and {nb} (UniProt {b}) bind each other. Use the "
            f"tools to gather evidence, then predict for EACH protein the region of its sequence that "
            f"forms the interface (UniProt numbering). Tools with no data report 'pending'; never "
            f"invent residues or scores. Submit with submit_adjudication and fill predicted_regions.")
    return Case(id=f"custom_{a}_{b}", name_a=na, uniprot_a=a, name_b=nb, uniprot_b=b, goal=goal,
                literature_query=f"{na} {nb} interaction binding region", custom=True)
